/*
 * bygg - Component-based HTML/CSS builder for C++
 *
 * Copyright 2024-2025 - Jacob Nilsson & contributors
 * SPDX-License-Identifier: MIT
 */

#include <bygg/except.hpp>
#include <bygg/HTML/tag.hpp>
#include <algorithm>

std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> bygg::HTML::get_tag_map() {
    return {
        {Tag::Empty, {"", Type::Text}},
        {Tag::Empty_No_Formatting, {"", Type::Text_No_Formatting}},
        {Tag::Abbreviation, {"abbr", Type::Data}},
        {Tag::Abbr, {"abbr", Type::Data}},
        {Tag::Acronym, {"acronym", Type::Data}},
        {Tag::Address, {"address", Type::Data}},
        {Tag::Applet, {"applet", Type::Data}},
        {Tag::Anchor, {"a", Type::Data}},
        {Tag::A, {"a", Type::Data}},
        {Tag::Article, {"article", Type::Data}},
        {Tag::Area, {"area", Type::Standalone}},
        {Tag::Aside, {"aside", Type::Data}},
        {Tag::Audio, {"audio", Type::Data}},
        {Tag::Base, {"base", Type::Standalone}},
        {Tag::Basefont, {"basefont", Type::Standalone}},
        {Tag::Bdi, {"bdi", Type::Data}},
        {Tag::Bdo, {"bdo", Type::Data}},
        {Tag::Bgsound, {"bgsound", Type::Data}},
        {Tag::Big, {"big", Type::Data}},
        {Tag::Blockquote, {"blockquote", Type::Data}},
        {Tag::Body, {"body", Type::Data}},
        {Tag::B, {"b", Type::Data}},
        {Tag::Bold, {"b", Type::Data}},
        {Tag::Br, {"br", Type::Standalone}},
        {Tag::Break, {"br", Type::Standalone}},
        {Tag::Button, {"button", Type::Data}},
        {Tag::Caption, {"caption", Type::Data}},
        {Tag::Canvas, {"canvas", Type::Data}},
        {Tag::Center, {"center", Type::Data}},
        {Tag::Cite, {"cite", Type::Data}},
        {Tag::Code, {"code", Type::Data}},
        {Tag::Colgroup, {"colgroup", Type::Data}},
        {Tag::Column, {"col", Type::Standalone}},
        {Tag::Col, {"col", Type::Standalone}},
        {Tag::Data, {"data", Type::Data}},
        {Tag::Datalist, {"datalist", Type::Data}},
        {Tag::Dd, {"dd", Type::Data}},
        {Tag::Dfn, {"dfn", Type::Data}},
        {Tag::Define, {"dfn", Type::Data}},
        {Tag::Delete, {"del", Type::Data}},
        {Tag::Del, {"del", Type::Data}},
        {Tag::Details, {"details", Type::Data}},
        {Tag::Dialog, {"dialog", Type::Data}},
        {Tag::Dir, {"dir", Type::Data}},
        {Tag::Div, {"div", Type::Data}},
        {Tag::Dl, {"dl", Type::Data}},
        {Tag::Dt, {"dt", Type::Data}},
        {Tag::Embed, {"embed", Type::Standalone}},
        {Tag::Emphasis, {"em", Type::Data}},
        {Tag::Em, {"em", Type::Data}},
        {Tag::Fieldset, {"fieldset", Type::Data}},
        {Tag::Figcaption, {"figcaption", Type::Data}},
        {Tag::Figure, {"figure", Type::Data}},
        {Tag::Font, {"font", Type::Data}},
        {Tag::Footer, {"footer", Type::Data}},
        {Tag::Form, {"form", Type::Data}},
        {Tag::Frame, {"frame", Type::Standalone}},
        {Tag::Frameset, {"frameset", Type::Data}},
        {Tag::Head, {"head", Type::Data}},
        {Tag::Header, {"header", Type::Data}},
        {Tag::H1, {"h1", Type::Data}},
        {Tag::H2, {"h2", Type::Data}},
        {Tag::H3, {"h3", Type::Data}},
        {Tag::H4, {"h4", Type::Data}},
        {Tag::H5, {"h5", Type::Data}},
        {Tag::H6, {"h6", Type::Data}},
        {Tag::Hr, {"hr", Type::Standalone}},
        {Tag::Hgroup, {"hgroup", Type::Data}},
        {Tag::Html, {"html", Type::Data}},
        {Tag::Iframe, {"iframe", Type::Data}},
        {Tag::Image, {"img", Type::Standalone}},
        {Tag::Img, {"img", Type::Standalone}},
        {Tag::Input, {"input", Type::Standalone}},
        {Tag::Ins, {"ins", Type::Data}},
        {Tag::Isindex, {"isindex", Type::Standalone}},
        {Tag::Italic, {"i", Type::Data}},
        {Tag::I, {"i", Type::Data}},
        {Tag::Kbd, {"kbd", Type::Data}},
        {Tag::Keygen, {"keygen", Type::Standalone}},
        {Tag::Label, {"label", Type::Data}},
        {Tag::Legend, {"legend", Type::Data}},
        {Tag::List, {"li", Type::Data}},
        {Tag::Li, {"li", Type::Data}},
        {Tag::Link, {"link", Type::Standalone}},
        {Tag::Main, {"main", Type::Data}},
        {Tag::Mark, {"mark", Type::Data}},
        {Tag::Marquee, {"marquee", Type::Data}},
        {Tag::Menuitem, {"menuitem", Type::Data}},
        {Tag::Meta, {"meta", Type::Standalone}},
        {Tag::Meter, {"meter", Type::Data}},
        {Tag::Nav, {"nav", Type::Data}},
        {Tag::Nobreak, {"nobr", Type::Data}},
        {Tag::Nobr, {"nobr", Type::Data}},
        {Tag::Noembed, {"noembed", Type::Data}},
        {Tag::Noscript, {"noscript", Type::Data}},
        {Tag::Object, {"object", Type::Data}},
        {Tag::Optgroup, {"optgroup", Type::Data}},
        {Tag::Option, {"option", Type::Data}},
        {Tag::Output, {"output", Type::Data}},
        {Tag::Paragraph, {"p", Type::Data}},
        {Tag::P, {"p", Type::Data}},
        {Tag::Param, {"param", Type::Standalone}},
        {Tag::Phrase, {"phrase", Type::Data}},
        {Tag::Pre, {"pre", Type::Data}},
        {Tag::Progress, {"progress", Type::Data}},
        {Tag::Quote, {"q", Type::Data}},
        {Tag::Q, {"q", Type::Data}},
        {Tag::Rp, {"rp", Type::Data}},
        {Tag::Rt, {"rt", Type::Data}},
        {Tag::Ruby, {"ruby", Type::Data}},
        {Tag::Outdated, {"s", Type::Data}},
        {Tag::S, {"s", Type::Data}},
        {Tag::Sample, {"samp", Type::Data}},
        {Tag::Samp, {"samp", Type::Data}},
        {Tag::Script, {"script", Type::Data}},
        {Tag::Section, {"section", Type::Data}},
        {Tag::Small, {"small", Type::Data}},
        {Tag::Source, {"source", Type::Data}},
        {Tag::Spacer, {"spacer", Type::Data}},
        {Tag::Span, {"span", Type::Data}},
        {Tag::Strike, {"strike", Type::Data}},
        {Tag::Strong, {"strong", Type::Data}},
        {Tag::Style, {"style", Type::Data}},
        {Tag::Sub, {"sub", Type::Data}},
        {Tag::Subscript, {"sub", Type::Data}},
        {Tag::Sup, {"sup", Type::Data}},
        {Tag::Superscript, {"sup", Type::Data}},
        {Tag::Summary, {"summary", Type::Data}},
        {Tag::Svg, {"svg", Type::Standalone}},
        {Tag::Table, {"table", Type::Data}},
        {Tag::Tbody, {"tbody", Type::Data}},
        {Tag::Td, {"td", Type::Data}},
        {Tag::Template, {"template", Type::Data}},
        {Tag::Tfoot, {"tfoot", Type::Data}},
        {Tag::Th, {"th", Type::Data}},
        {Tag::Tr, {"tr", Type::Data}},
        {Tag::Thead, {"thead", Type::Data}},
        {Tag::Time, {"time", Type::Data}},
        {Tag::Title, {"title", Type::Data}},
        {Tag::Track, {"track", Type::Standalone}},
        {Tag::Tt, {"tt", Type::Data}},
        {Tag::Underline, {"u", Type::Data}},
        {Tag::U, {"u", Type::Data}},
        {Tag::Var, {"var", Type::Data}},
        {Tag::Video, {"video", Type::Data}},
        {Tag::Wbr, {"wbr", Type::Standalone}},
        {Tag::Xmp, {"xmp", Type::Data}},
    };
}

bygg::string_type bygg::HTML::resolve_tag_enum_name(bygg::HTML::Tag tag) {
    static const std::unordered_map<Tag, std::string> tag_string_map = {
        {Tag::Empty, "Tag::Empty"},
        {Tag::Empty_No_Formatting, "Tag::Empty_No_Formatting"},
        {Tag::Abbreviation, "Tag::Abbreviation"},
        {Tag::Abbr, "Tag::Abbr"},
        {Tag::Acronym, "Tag::Acronym"},
        {Tag::Address, "Tag::Address"},
        {Tag::Applet, "Tag::Applet"},
        {Tag::Anchor, "Tag::Anchor"},
        {Tag::A, "Tag::A"},
        {Tag::Article, "Tag::Article"},
        {Tag::Area, "Tag::Area"},
        {Tag::Aside, "Tag::Aside"},
        {Tag::Audio, "Tag::Audio"},
        {Tag::Base, "Tag::Base"},
        {Tag::Basefont, "Tag::Basefont"},
        {Tag::Bdi, "Tag::Bdi"},
        {Tag::Bdo, "Tag::Bdo"},
        {Tag::Bgsound, "Tag::Bgsound"},
        {Tag::Big, "Tag::Big"},
        {Tag::Blockquote, "Tag::Blockquote"},
        {Tag::Body, "Tag::Body"},
        {Tag::B, "Tag::B"},
        {Tag::Bold, "Tag::Bold"},
        {Tag::Br, "Tag::Br"},
        {Tag::Break, "Tag::Break"},
        {Tag::Button, "Tag::Button"},
        {Tag::Caption, "Tag::Caption"},
        {Tag::Canvas, "Tag::Canvas"},
        {Tag::Center, "Tag::Center"},
        {Tag::Cite, "Tag::Cite"},
        {Tag::Code, "Tag::Code"},
        {Tag::Colgroup, "Tag::Colgroup"},
        {Tag::Column, "Tag::Column"},
        {Tag::Col, "Tag::Col"},
        {Tag::Data, "Tag::Data"},
        {Tag::Datalist, "Tag::Datalist"},
        {Tag::Dd, "Tag::Dd"},
        {Tag::Dfn, "Tag::Dfn"},
        {Tag::Define, "Tag::Define"},
        {Tag::Delete, "Tag::Delete"},
        {Tag::Del, "Tag::Del"},
        {Tag::Details, "Tag::Details"},
        {Tag::Dialog, "Tag::Dialog"},
        {Tag::Dir, "Tag::Dir"},
        {Tag::Div, "Tag::Div"},
        {Tag::Dl, "Tag::Dl"},
        {Tag::Dt, "Tag::Dt"},
        {Tag::Embed, "Tag::Embed"},
        {Tag::Emphasis, "Tag::Emphasis"},
        {Tag::Em, "Tag::Em"},
        {Tag::Fieldset, "Tag::Fieldset"},
        {Tag::Figcaption, "Tag::Figcaption"},
        {Tag::Figure, "Tag::Figure"},
        {Tag::Font, "Tag::Font"},
        {Tag::Footer, "Tag::Footer"},
        {Tag::Form, "Tag::Form"},
        {Tag::Frame, "Tag::Frame"},
        {Tag::Frameset, "Tag::Frameset"},
        {Tag::Head, "Tag::Head"},
        {Tag::Header, "Tag::Header"},
        {Tag::H1, "Tag::H1"},
        {Tag::H2, "Tag::H2"},
        {Tag::H3, "Tag::H3"},
        {Tag::H4, "Tag::H4"},
        {Tag::H5, "Tag::H5"},
        {Tag::H6, "Tag::H6"},
        {Tag::Hr, "Tag::Hr"},
        {Tag::Hgroup, "Tag::Hgroup"},
        {Tag::Html, "Tag::Html"},
        {Tag::Iframe, "Tag::Iframe"},
        {Tag::Image, "Tag::Image"},
        {Tag::Img, "Tag::Img"},
        {Tag::Input, "Tag::Input"},
        {Tag::Ins, "Tag::Ins"},
        {Tag::Isindex, "Tag::Isindex"},
        {Tag::Italic, "Tag::Italic"},
        {Tag::I, "Tag::I"},
        {Tag::Kbd, "Tag::Kbd"},
        {Tag::Keygen, "Tag::Keygen"},
        {Tag::Label, "Tag::Label"},
        {Tag::Legend, "Tag::Legend"},
        {Tag::List, "Tag::List"},
        {Tag::Li, "Tag::Li"},
        {Tag::Link, "Tag::Link"},
        {Tag::Main, "Tag::Main"},
        {Tag::Mark, "Tag::Mark"},
        {Tag::Marquee, "Tag::Marquee"},
        {Tag::Menuitem, "Tag::Menuitem"},
        {Tag::Meta, "Tag::Meta"},
        {Tag::Meter, "Tag::Meter"},
        {Tag::Nav, "Tag::Nav"},
        {Tag::Nobreak, "Tag::Nobreak"},
        {Tag::Nobr, "Tag::Nobr"},
        {Tag::Noembed, "Tag::Noembed"},
        {Tag::Noscript, "Tag::Noscript"},
        {Tag::Object, "Tag::Object"},
        {Tag::Optgroup, "Tag::Optgroup"},
        {Tag::Option, "Tag::Option"},
        {Tag::Output, "Tag::Output"},
        {Tag::Paragraph, "Tag::Paragraph"},
        {Tag::P, "Tag::P"},
        {Tag::Param, "Tag::Param"},
        {Tag::Phrase, "Tag::Phrase"},
        {Tag::Pre, "Tag::Pre"},
        {Tag::Progress, "Tag::Progress"},
        {Tag::Quote, "Tag::Quote"},
        {Tag::Q, "Tag::Q"},
        {Tag::Rp, "Tag::Rp"},
        {Tag::Rt, "Tag::Rt"},
        {Tag::Ruby, "Tag::Ruby"},
        {Tag::Outdated, "Tag::Outdated"},
        {Tag::S, "Tag::S"},
        {Tag::Sample, "Tag::Sample"},
        {Tag::Samp, "Tag::Samp"},
        {Tag::Script, "Tag::Script"},
        {Tag::Section, "Tag::Section"},
        {Tag::Small, "Tag::Small"},
        {Tag::Source, "Tag::Source"},
        {Tag::Spacer, "Tag::Spacer"},
        {Tag::Span, "Tag::Span"},
        {Tag::Strike, "Tag::Strike"},
        {Tag::Strong, "Tag::Strong"},
        {Tag::Style, "Tag::Style"},
        {Tag::Sub, "Tag::Sub"},
        {Tag::Subscript, "Tag::Subscript"},
        {Tag::Sup, "Tag::Sup"},
        {Tag::Superscript, "Tag::Superscript"},
        {Tag::Summary, "Tag::Summary"},
        {Tag::Svg, "Tag::Svg"},
        {Tag::Table, "Tag::Table"},
        {Tag::Tbody, "Tag::Tbody"},
        {Tag::Td, "Tag::Td"},
        {Tag::Template, "Tag::Template"},
        {Tag::Tfoot, "Tag::Tfoot"},
        {Tag::Th, "Tag::Th"},
        {Tag::Tr, "Tag::Tr"},
        {Tag::Thead, "Tag::Thead"},
        {Tag::Time, "Tag::Time"},
        {Tag::Title, "Tag::Title"},
        {Tag::Track, "Tag::Track"},
        {Tag::Tt, "Tag::Tt"},
        {Tag::Underline, "Tag::Underline"},
        {Tag::U, "Tag::U"},
        {Tag::Var, "Tag::Var"},
        {Tag::Video, "Tag::Video"},
        {Tag::Wbr, "Tag::Wbr"},
        {Tag::Xmp, "Tag::Xmp"},
    };

    if (tag_string_map.find(tag) != tag_string_map.end()) {
        return tag_string_map.at(tag);
    }

    throw bygg::invalid_argument{"Invalid tag"};
}

std::pair<bygg::string_type, bygg::HTML::Type> bygg::HTML::resolve_tag(const Tag tag) {
    const std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> tag_map{get_tag_map()};

    if (tag_map.find(tag) != tag_map.end()) {
        return tag_map.at(tag);
    }

    const string_type throwmsg{"Invalid tag: " + std::to_string(static_cast<bygg::integer_type>(tag))};
    throw invalid_argument{throwmsg.c_str()};
}

bygg::HTML::Tag bygg::HTML::resolve_tag(const bygg::string_type& tag) {
    const std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> tag_map{get_tag_map()};

    for (const auto& it : tag_map) {
        if (it.second.first == tag) {
            return it.first;
        }
    }

    throw invalid_argument{"Invalid tag"};
}

bool bygg::HTML::is_container(const string_type& tag) {
    static const std::vector<std::string> container_elements = {
        "div",
        "section",
        "article",
        "nav",
        "aside",
        "head",
        "header",
        "footer",
        "foot",
        "main",
        "ul",
        "ol",
        "li",
        "body",
        "table",
        "tbody",
        "thead",
        "tfoot",
        "tr",
        "td",
        "th",
        "form",
        "fieldset",
        "details",
        "summary",
        "html",
    };

    return std::find(container_elements.begin(), container_elements.end(), tag) != container_elements.end();
}

bool bygg::HTML::is_container(Tag tag) {
    return is_container(resolve_tag(tag).first);
}