/*
 * bygg - Component-based HTML/CSS builder for C++
 *
 * Copyright 2024 - Jacob Nilsson & contributors
 * SPDX-License-Identifier: MIT
 */

#include <bygg/except.hpp>
#include <bygg/HTML/tag.hpp>
#include <algorithm>

std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> bygg::HTML::get_tag_map() {
    return {
        {Tag::Empty, {"", Type::Text}},
        {Tag::Empty_No_Formatting, {"", Type::Text_No_Formatting}},
        {Tag::Abbreviation, {"abbr", Type::Non_Self_Closing}},
        {Tag::Abbr, {"abbr", Type::Non_Self_Closing}},
        {Tag::Acronym, {"acronym", Type::Non_Self_Closing}},
        {Tag::Address, {"address", Type::Non_Self_Closing}},
        {Tag::Applet, {"applet", Type::Non_Self_Closing}},
        {Tag::Anchor, {"a", Type::Non_Self_Closing}},
        {Tag::A, {"a", Type::Non_Self_Closing}},
        {Tag::Article, {"article", Type::Non_Self_Closing}},
        {Tag::Area, {"area", Type::Self_Closing}},
        {Tag::Aside, {"aside", Type::Non_Self_Closing}},
        {Tag::Audio, {"audio", Type::Non_Self_Closing}},
        {Tag::Base, {"base", Type::Self_Closing}},
        {Tag::Basefont, {"basefont", Type::Self_Closing}},
        {Tag::Bdi, {"bdi", Type::Non_Self_Closing}},
        {Tag::Bdo, {"bdo", Type::Non_Self_Closing}},
        {Tag::Bgsound, {"bgsound", Type::Non_Self_Closing}},
        {Tag::Big, {"big", Type::Non_Self_Closing}},
        {Tag::Blockquote, {"blockquote", Type::Non_Self_Closing}},
        {Tag::Body, {"body", Type::Non_Self_Closing}},
        {Tag::B, {"b", Type::Non_Self_Closing}},
        {Tag::Bold, {"b", Type::Non_Self_Closing}},
        {Tag::Br, {"br", Type::Self_Closing}},
        {Tag::Break, {"br", Type::Self_Closing}},
        {Tag::Button, {"button", Type::Non_Self_Closing}},
        {Tag::Caption, {"caption", Type::Non_Self_Closing}},
        {Tag::Canvas, {"canvas", Type::Non_Self_Closing}},
        {Tag::Center, {"center", Type::Non_Self_Closing}},
        {Tag::Cite, {"cite", Type::Non_Self_Closing}},
        {Tag::Code, {"code", Type::Non_Self_Closing}},
        {Tag::Colgroup, {"colgroup", Type::Non_Self_Closing}},
        {Tag::Column, {"col", Type::Self_Closing}},
        {Tag::Col, {"col", Type::Self_Closing}},
        {Tag::Data, {"data", Type::Non_Self_Closing}},
        {Tag::Datalist, {"datalist", Type::Non_Self_Closing}},
        {Tag::Dd, {"dd", Type::Non_Self_Closing}},
        {Tag::Dfn, {"dfn", Type::Non_Self_Closing}},
        {Tag::Define, {"dfn", Type::Non_Self_Closing}},
        {Tag::Delete, {"del", Type::Non_Self_Closing}},
        {Tag::Del, {"del", Type::Non_Self_Closing}},
        {Tag::Details, {"details", Type::Non_Self_Closing}},
        {Tag::Dialog, {"dialog", Type::Non_Self_Closing}},
        {Tag::Dir, {"dir", Type::Non_Self_Closing}},
        {Tag::Div, {"div", Type::Non_Self_Closing}},
        {Tag::Dl, {"dl", Type::Non_Self_Closing}},
        {Tag::Dt, {"dt", Type::Non_Self_Closing}},
        {Tag::Embed, {"embed", Type::Self_Closing}},
        {Tag::Emphasis, {"em", Type::Non_Self_Closing}},
        {Tag::Em, {"em", Type::Non_Self_Closing}},
        {Tag::Fieldset, {"fieldset", Type::Non_Self_Closing}},
        {Tag::Figcaption, {"figcaption", Type::Non_Self_Closing}},
        {Tag::Figure, {"figure", Type::Non_Self_Closing}},
        {Tag::Font, {"font", Type::Non_Self_Closing}},
        {Tag::Footer, {"footer", Type::Non_Self_Closing}},
        {Tag::Form, {"form", Type::Non_Self_Closing}},
        {Tag::Frame, {"frame", Type::Self_Closing}},
        {Tag::Frameset, {"frameset", Type::Non_Self_Closing}},
        {Tag::Head, {"head", Type::Non_Self_Closing}},
        {Tag::Header, {"header", Type::Non_Self_Closing}},
        {Tag::H1, {"h1", Type::Non_Self_Closing}},
        {Tag::H2, {"h2", Type::Non_Self_Closing}},
        {Tag::H3, {"h3", Type::Non_Self_Closing}},
        {Tag::H4, {"h4", Type::Non_Self_Closing}},
        {Tag::H5, {"h5", Type::Non_Self_Closing}},
        {Tag::H6, {"h6", Type::Non_Self_Closing}},
        {Tag::Hr, {"hr", Type::Self_Closing}},
        {Tag::Hgroup, {"hgroup", Type::Non_Self_Closing}},
        {Tag::Html, {"html", Type::Non_Self_Closing}},
        {Tag::Iframe, {"iframe", Type::Non_Self_Closing}},
        {Tag::Image, {"img", Type::Self_Closing}},
        {Tag::Img, {"img", Type::Self_Closing}},
        {Tag::Input, {"input", Type::Self_Closing}},
        {Tag::Ins, {"ins", Type::Non_Self_Closing}},
        {Tag::Isindex, {"isindex", Type::Self_Closing}},
        {Tag::Italic, {"i", Type::Non_Self_Closing}},
        {Tag::I, {"i", Type::Non_Self_Closing}},
        {Tag::Kbd, {"kbd", Type::Non_Self_Closing}},
        {Tag::Keygen, {"keygen", Type::Self_Closing}},
        {Tag::Label, {"label", Type::Non_Self_Closing}},
        {Tag::Legend, {"legend", Type::Non_Self_Closing}},
        {Tag::List, {"li", Type::Non_Self_Closing}},
        {Tag::Li, {"li", Type::Non_Self_Closing}},
        {Tag::Link, {"link", Type::Self_Closing}},
        {Tag::Main, {"main", Type::Non_Self_Closing}},
        {Tag::Mark, {"mark", Type::Non_Self_Closing}},
        {Tag::Marquee, {"marquee", Type::Non_Self_Closing}},
        {Tag::Menuitem, {"menuitem", Type::Non_Self_Closing}},
        {Tag::Meta, {"meta", Type::Self_Closing}},
        {Tag::Meter, {"meter", Type::Non_Self_Closing}},
        {Tag::Nav, {"nav", Type::Non_Self_Closing}},
        {Tag::Nobreak, {"nobr", Type::Non_Self_Closing}},
        {Tag::Nobr, {"nobr", Type::Non_Self_Closing}},
        {Tag::Noembed, {"noembed", Type::Non_Self_Closing}},
        {Tag::Noscript, {"noscript", Type::Non_Self_Closing}},
        {Tag::Object, {"object", Type::Non_Self_Closing}},
        {Tag::Optgroup, {"optgroup", Type::Non_Self_Closing}},
        {Tag::Option, {"option", Type::Non_Self_Closing}},
        {Tag::Output, {"output", Type::Non_Self_Closing}},
        {Tag::Paragraph, {"p", Type::Non_Self_Closing}},
        {Tag::P, {"p", Type::Non_Self_Closing}},
        {Tag::Param, {"param", Type::Self_Closing}},
        {Tag::Phrase, {"phrase", Type::Non_Self_Closing}},
        {Tag::Pre, {"pre", Type::Non_Self_Closing}},
        {Tag::Progress, {"progress", Type::Non_Self_Closing}},
        {Tag::Quote, {"q", Type::Non_Self_Closing}},
        {Tag::Q, {"q", Type::Non_Self_Closing}},
        {Tag::Rp, {"rp", Type::Non_Self_Closing}},
        {Tag::Rt, {"rt", Type::Non_Self_Closing}},
        {Tag::Ruby, {"ruby", Type::Non_Self_Closing}},
        {Tag::Outdated, {"s", Type::Non_Self_Closing}},
        {Tag::S, {"s", Type::Non_Self_Closing}},
        {Tag::Sample, {"samp", Type::Non_Self_Closing}},
        {Tag::Samp, {"samp", Type::Non_Self_Closing}},
        {Tag::Script, {"script", Type::Non_Self_Closing}},
        {Tag::Section, {"section", Type::Non_Self_Closing}},
        {Tag::Small, {"small", Type::Non_Self_Closing}},
        {Tag::Source, {"source", Type::Non_Self_Closing}},
        {Tag::Spacer, {"spacer", Type::Non_Self_Closing}},
        {Tag::Span, {"span", Type::Non_Self_Closing}},
        {Tag::Strike, {"strike", Type::Non_Self_Closing}},
        {Tag::Strong, {"strong", Type::Non_Self_Closing}},
        {Tag::Style, {"style", Type::Non_Self_Closing}},
        {Tag::Sub, {"sub", Type::Non_Self_Closing}},
        {Tag::Subscript, {"sub", Type::Non_Self_Closing}},
        {Tag::Sup, {"sup", Type::Non_Self_Closing}},
        {Tag::Superscript, {"sup", Type::Non_Self_Closing}},
        {Tag::Summary, {"summary", Type::Non_Self_Closing}},
        {Tag::Svg, {"svg", Type::Self_Closing}},
        {Tag::Table, {"table", Type::Non_Self_Closing}},
        {Tag::Tbody, {"tbody", Type::Non_Self_Closing}},
        {Tag::Td, {"td", Type::Non_Self_Closing}},
        {Tag::Template, {"template", Type::Non_Self_Closing}},
        {Tag::Tfoot, {"tfoot", Type::Non_Self_Closing}},
        {Tag::Th, {"th", Type::Non_Self_Closing}},
        {Tag::Tr, {"tr", Type::Non_Self_Closing}},
        {Tag::Thead, {"thead", Type::Non_Self_Closing}},
        {Tag::Time, {"time", Type::Non_Self_Closing}},
        {Tag::Title, {"title", Type::Non_Self_Closing}},
        {Tag::Track, {"track", Type::Self_Closing}},
        {Tag::Tt, {"tt", Type::Non_Self_Closing}},
        {Tag::Underline, {"u", Type::Non_Self_Closing}},
        {Tag::U, {"u", Type::Non_Self_Closing}},
        {Tag::Var, {"var", Type::Non_Self_Closing}},
        {Tag::Video, {"video", Type::Non_Self_Closing}},
        {Tag::Wbr, {"wbr", Type::Self_Closing}},
        {Tag::Xmp, {"xmp", Type::Non_Self_Closing}},
    };
}

bygg::string_type bygg::HTML::resolve_tag_enum_name(bygg::HTML::Tag tag) {
    static const std::unordered_map<bygg::HTML::Tag, std::string> tag_string_map = {
        {bygg::HTML::Tag::Empty, "bygg::HTML::Tag::Empty"},
        {bygg::HTML::Tag::Empty_No_Formatting, "bygg::HTML::Tag::Empty_No_Formatting"},
        {bygg::HTML::Tag::Abbreviation, "bygg::HTML::Tag::Abbreviation"},
        {bygg::HTML::Tag::Abbr, "bygg::HTML::Tag::Abbr"},
        {bygg::HTML::Tag::Acronym, "bygg::HTML::Tag::Acronym"},
        {bygg::HTML::Tag::Address, "bygg::HTML::Tag::Address"},
        {bygg::HTML::Tag::Applet, "bygg::HTML::Tag::Applet"},
        {bygg::HTML::Tag::Anchor, "bygg::HTML::Tag::Anchor"},
        {bygg::HTML::Tag::A, "bygg::HTML::Tag::A"},
        {bygg::HTML::Tag::Article, "bygg::HTML::Tag::Article"},
        {bygg::HTML::Tag::Area, "bygg::HTML::Tag::Area"},
        {bygg::HTML::Tag::Aside, "bygg::HTML::Tag::Aside"},
        {bygg::HTML::Tag::Audio, "bygg::HTML::Tag::Audio"},
        {bygg::HTML::Tag::Base, "bygg::HTML::Tag::Base"},
        {bygg::HTML::Tag::Basefont, "bygg::HTML::Tag::Basefont"},
        {bygg::HTML::Tag::Bdi, "bygg::HTML::Tag::Bdi"},
        {bygg::HTML::Tag::Bdo, "bygg::HTML::Tag::Bdo"},
        {bygg::HTML::Tag::Bgsound, "bygg::HTML::Tag::Bgsound"},
        {bygg::HTML::Tag::Big, "bygg::HTML::Tag::Big"},
        {bygg::HTML::Tag::Blockquote, "bygg::HTML::Tag::Blockquote"},
        {bygg::HTML::Tag::Body, "bygg::HTML::Tag::Body"},
        {bygg::HTML::Tag::B, "bygg::HTML::Tag::B"},
        {bygg::HTML::Tag::Bold, "bygg::HTML::Tag::Bold"},
        {bygg::HTML::Tag::Br, "bygg::HTML::Tag::Br"},
        {bygg::HTML::Tag::Break, "bygg::HTML::Tag::Break"},
        {bygg::HTML::Tag::Button, "bygg::HTML::Tag::Button"},
        {bygg::HTML::Tag::Caption, "bygg::HTML::Tag::Caption"},
        {bygg::HTML::Tag::Canvas, "bygg::HTML::Tag::Canvas"},
        {bygg::HTML::Tag::Center, "bygg::HTML::Tag::Center"},
        {bygg::HTML::Tag::Cite, "bygg::HTML::Tag::Cite"},
        {bygg::HTML::Tag::Code, "bygg::HTML::Tag::Code"},
        {bygg::HTML::Tag::Colgroup, "bygg::HTML::Tag::Colgroup"},
        {bygg::HTML::Tag::Column, "bygg::HTML::Tag::Column"},
        {bygg::HTML::Tag::Col, "bygg::HTML::Tag::Col"},
        {bygg::HTML::Tag::Data, "bygg::HTML::Tag::Data"},
        {bygg::HTML::Tag::Datalist, "bygg::HTML::Tag::Datalist"},
        {bygg::HTML::Tag::Dd, "bygg::HTML::Tag::Dd"},
        {bygg::HTML::Tag::Dfn, "bygg::HTML::Tag::Dfn"},
        {bygg::HTML::Tag::Define, "bygg::HTML::Tag::Define"},
        {bygg::HTML::Tag::Delete, "bygg::HTML::Tag::Delete"},
        {bygg::HTML::Tag::Del, "bygg::HTML::Tag::Del"},
        {bygg::HTML::Tag::Details, "bygg::HTML::Tag::Details"},
        {bygg::HTML::Tag::Dialog, "bygg::HTML::Tag::Dialog"},
        {bygg::HTML::Tag::Dir, "bygg::HTML::Tag::Dir"},
        {bygg::HTML::Tag::Div, "bygg::HTML::Tag::Div"},
        {bygg::HTML::Tag::Dl, "bygg::HTML::Tag::Dl"},
        {bygg::HTML::Tag::Dt, "bygg::HTML::Tag::Dt"},
        {bygg::HTML::Tag::Embed, "bygg::HTML::Tag::Embed"},
        {bygg::HTML::Tag::Emphasis, "bygg::HTML::Tag::Emphasis"},
        {bygg::HTML::Tag::Em, "bygg::HTML::Tag::Em"},
        {bygg::HTML::Tag::Fieldset, "bygg::HTML::Tag::Fieldset"},
        {bygg::HTML::Tag::Figcaption, "bygg::HTML::Tag::Figcaption"},
        {bygg::HTML::Tag::Figure, "bygg::HTML::Tag::Figure"},
        {bygg::HTML::Tag::Font, "bygg::HTML::Tag::Font"},
        {bygg::HTML::Tag::Footer, "bygg::HTML::Tag::Footer"},
        {bygg::HTML::Tag::Form, "bygg::HTML::Tag::Form"},
        {bygg::HTML::Tag::Frame, "bygg::HTML::Tag::Frame"},
        {bygg::HTML::Tag::Frameset, "bygg::HTML::Tag::Frameset"},
        {bygg::HTML::Tag::Head, "bygg::HTML::Tag::Head"},
        {bygg::HTML::Tag::Header, "bygg::HTML::Tag::Header"},
        {bygg::HTML::Tag::H1, "bygg::HTML::Tag::H1"},
        {bygg::HTML::Tag::H2, "bygg::HTML::Tag::H2"},
        {bygg::HTML::Tag::H3, "bygg::HTML::Tag::H3"},
        {bygg::HTML::Tag::H4, "bygg::HTML::Tag::H4"},
        {bygg::HTML::Tag::H5, "bygg::HTML::Tag::H5"},
        {bygg::HTML::Tag::H6, "bygg::HTML::Tag::H6"},
        {bygg::HTML::Tag::Hr, "bygg::HTML::Tag::Hr"},
        {bygg::HTML::Tag::Hgroup, "bygg::HTML::Tag::Hgroup"},
        {bygg::HTML::Tag::Html, "bygg::HTML::Tag::Html"},
        {bygg::HTML::Tag::Iframe, "bygg::HTML::Tag::Iframe"},
        {bygg::HTML::Tag::Image, "bygg::HTML::Tag::Image"},
        {bygg::HTML::Tag::Img, "bygg::HTML::Tag::Img"},
        {bygg::HTML::Tag::Input, "bygg::HTML::Tag::Input"},
        {bygg::HTML::Tag::Ins, "bygg::HTML::Tag::Ins"},
        {bygg::HTML::Tag::Isindex, "bygg::HTML::Tag::Isindex"},
        {bygg::HTML::Tag::Italic, "bygg::HTML::Tag::Italic"},
        {bygg::HTML::Tag::I, "bygg::HTML::Tag::I"},
        {bygg::HTML::Tag::Kbd, "bygg::HTML::Tag::Kbd"},
        {bygg::HTML::Tag::Keygen, "bygg::HTML::Tag::Keygen"},
        {bygg::HTML::Tag::Label, "bygg::HTML::Tag::Label"},
        {bygg::HTML::Tag::Legend, "bygg::HTML::Tag::Legend"},
        {bygg::HTML::Tag::List, "bygg::HTML::Tag::List"},
        {bygg::HTML::Tag::Li, "bygg::HTML::Tag::Li"},
        {bygg::HTML::Tag::Link, "bygg::HTML::Tag::Link"},
        {bygg::HTML::Tag::Main, "bygg::HTML::Tag::Main"},
        {bygg::HTML::Tag::Mark, "bygg::HTML::Tag::Mark"},
        {bygg::HTML::Tag::Marquee, "bygg::HTML::Tag::Marquee"},
        {bygg::HTML::Tag::Menuitem, "bygg::HTML::Tag::Menuitem"},
        {bygg::HTML::Tag::Meta, "bygg::HTML::Tag::Meta"},
        {bygg::HTML::Tag::Meter, "bygg::HTML::Tag::Meter"},
        {bygg::HTML::Tag::Nav, "bygg::HTML::Tag::Nav"},
        {bygg::HTML::Tag::Nobreak, "bygg::HTML::Tag::Nobreak"},
        {bygg::HTML::Tag::Nobr, "bygg::HTML::Tag::Nobr"},
        {bygg::HTML::Tag::Noembed, "bygg::HTML::Tag::Noembed"},
        {bygg::HTML::Tag::Noscript, "bygg::HTML::Tag::Noscript"},
        {bygg::HTML::Tag::Object, "bygg::HTML::Tag::Object"},
        {bygg::HTML::Tag::Optgroup, "bygg::HTML::Tag::Optgroup"},
        {bygg::HTML::Tag::Option, "bygg::HTML::Tag::Option"},
        {bygg::HTML::Tag::Output, "bygg::HTML::Tag::Output"},
        {bygg::HTML::Tag::Paragraph, "bygg::HTML::Tag::Paragraph"},
        {bygg::HTML::Tag::P, "bygg::HTML::Tag::P"},
        {bygg::HTML::Tag::Param, "bygg::HTML::Tag::Param"},
        {bygg::HTML::Tag::Phrase, "bygg::HTML::Tag::Phrase"},
        {bygg::HTML::Tag::Pre, "bygg::HTML::Tag::Pre"},
        {bygg::HTML::Tag::Progress, "bygg::HTML::Tag::Progress"},
        {bygg::HTML::Tag::Quote, "bygg::HTML::Tag::Quote"},
        {bygg::HTML::Tag::Q, "bygg::HTML::Tag::Q"},
        {bygg::HTML::Tag::Rp, "bygg::HTML::Tag::Rp"},
        {bygg::HTML::Tag::Rt, "bygg::HTML::Tag::Rt"},
        {bygg::HTML::Tag::Ruby, "bygg::HTML::Tag::Ruby"},
        {bygg::HTML::Tag::Outdated, "bygg::HTML::Tag::Outdated"},
        {bygg::HTML::Tag::S, "bygg::HTML::Tag::S"},
        {bygg::HTML::Tag::Sample, "bygg::HTML::Tag::Sample"},
        {bygg::HTML::Tag::Samp, "bygg::HTML::Tag::Samp"},
        {bygg::HTML::Tag::Script, "bygg::HTML::Tag::Script"},
        {bygg::HTML::Tag::Section, "bygg::HTML::Tag::Section"},
        {bygg::HTML::Tag::Small, "bygg::HTML::Tag::Small"},
        {bygg::HTML::Tag::Source, "bygg::HTML::Tag::Source"},
        {bygg::HTML::Tag::Spacer, "bygg::HTML::Tag::Spacer"},
        {bygg::HTML::Tag::Span, "bygg::HTML::Tag::Span"},
        {bygg::HTML::Tag::Strike, "bygg::HTML::Tag::Strike"},
        {bygg::HTML::Tag::Strong, "bygg::HTML::Tag::Strong"},
        {bygg::HTML::Tag::Style, "bygg::HTML::Tag::Style"},
        {bygg::HTML::Tag::Sub, "bygg::HTML::Tag::Sub"},
        {bygg::HTML::Tag::Subscript, "bygg::HTML::Tag::Subscript"},
        {bygg::HTML::Tag::Sup, "bygg::HTML::Tag::Sup"},
        {bygg::HTML::Tag::Superscript, "bygg::HTML::Tag::Superscript"},
        {bygg::HTML::Tag::Summary, "bygg::HTML::Tag::Summary"},
        {bygg::HTML::Tag::Svg, "bygg::HTML::Tag::Svg"},
        {bygg::HTML::Tag::Table, "bygg::HTML::Tag::Table"},
        {bygg::HTML::Tag::Tbody, "bygg::HTML::Tag::Tbody"},
        {bygg::HTML::Tag::Td, "bygg::HTML::Tag::Td"},
        {bygg::HTML::Tag::Template, "bygg::HTML::Tag::Template"},
        {bygg::HTML::Tag::Tfoot, "bygg::HTML::Tag::Tfoot"},
        {bygg::HTML::Tag::Th, "bygg::HTML::Tag::Th"},
        {bygg::HTML::Tag::Tr, "bygg::HTML::Tag::Tr"},
        {bygg::HTML::Tag::Thead, "bygg::HTML::Tag::Thead"},
        {bygg::HTML::Tag::Time, "bygg::HTML::Tag::Time"},
        {bygg::HTML::Tag::Title, "bygg::HTML::Tag::Title"},
        {bygg::HTML::Tag::Track, "bygg::HTML::Tag::Track"},
        {bygg::HTML::Tag::Tt, "bygg::HTML::Tag::Tt"},
        {bygg::HTML::Tag::Underline, "bygg::HTML::Tag::Underline"},
        {bygg::HTML::Tag::U, "bygg::HTML::Tag::U"},
        {bygg::HTML::Tag::Var, "bygg::HTML::Tag::Var"},
        {bygg::HTML::Tag::Video, "bygg::HTML::Tag::Video"},
        {bygg::HTML::Tag::Wbr, "bygg::HTML::Tag::Wbr"},
        {bygg::HTML::Tag::Xmp, "bygg::HTML::Tag::Xmp"},
    };

    if (tag_string_map.find(tag) != tag_string_map.end()) {
        return tag_string_map.at(tag);
    }

    throw bygg::invalid_argument{"Invalid tag"};
}

std::pair<bygg::string_type, bygg::HTML::Type> bygg::HTML::resolve_tag(const Tag tag) {
    const std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> tag_map{get_tag_map()};

    if (tag_map.find(tag) != tag_map.end()) {
        return tag_map.at(tag);
    }

    const string_type throwmsg{"Invalid tag: " + std::to_string(static_cast<bygg::integer_type>(tag))};
    throw invalid_argument{throwmsg.c_str()};
}

bygg::HTML::Tag bygg::HTML::resolve_tag(const bygg::string_type& tag) {
    const std::unordered_map<bygg::HTML::Tag, std::pair<bygg::string_type, bygg::HTML::Type>> tag_map{get_tag_map()};

    for (const auto& it : tag_map) {
        if (it.second.first == tag) {
            return it.first;
        }
    }

    throw invalid_argument{"Invalid tag"};
}

bool bygg::HTML::is_container(const string_type& tag) {
    static const std::vector<std::string> container_elements = {
        "div",
        "section",
        "article",
        "nav",
        "aside",
        "head",
        "header",
        "footer",
        "foot",
        "main",
        "ul",
        "ol",
        "li",
        "body",
        "table",
        "tbody",
        "thead",
        "tfoot",
        "tr",
        "td",
        "th",
        "form",
        "fieldset",
        "details",
        "summary",
        "html",
    };

    return std::find(container_elements.begin(), container_elements.end(), tag) != container_elements.end();
}

bool bygg::HTML::is_container(Tag tag) {
    return is_container(resolve_tag(tag).first);
}